export const ActionTypes = {
  GET_USERS: "GET_USERS",
  SET_USERS: "SET_USERS",
  SET_USER: "SET_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  GET_RESULTS: "GET_RESULTS",
  GET_RESULT: "GET_RESULT",
  GET_RESULTS_BY_USERID: "GET_RESULTS_BY_USERID",
  SET_RESULTS: "SET_RESULTS",
  SET_RESULT: "SET_RESULT",
  UPDATE_RESULT: "UPDATE_RESULT",
  DELETE_RESULT: "DELETE_RESULT",
}